---
abstract: 'Test RDF data for content, validity and equality, etc.'
author:
  - 'Kjetil Kjernsmo, C<< <kjetilk at cpan.org> >>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-RDF
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  RDF::Trine: 0.134
  Test::Builder::Module: 0
  Test::More: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-RDF
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kjetilk/Test-RDF.git
version: 0.22
