---
name: Test-RDF
version: 0.0.1
author:
  - Michael Hendricks  <michael@palmcluster.org>
abstract: test the validity of RDF data
license: perl
requires:
  RDF::Redland: 1.000101
build_requires:
  Test::More: 0
provides:
  Test::RDF:
    file: lib/Test/RDF.pm
    version: 0.0.1
generated_by: Module::Build version 0.2611
