---
abstract: 'Test RDF data for content, validity and equality, etc.'
author:
  - 'Kjetil Kjernsmo, C<< <kjetilk at cpan.org> >>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-RDF
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  RDF::Trine: 0.134
  Scalar::Util: 0
  Test::Builder::Module: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/kjetilk/Test-RDF/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kjetilk/Test-RDF
version: 1.00
