---
abstract: 'Test RDF data for validity and equality.'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::RDF
name: Test-RDF
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  RDF::Trine: 0.134
  Scalar::Util: 1.24
  Test::Builder::Module: 0
  Test::More: 0
  perl: 5.005
resources:
  bugtracker: https://github.com/kjetilk/Test-RDF/issues
  license: http://dev.perl.org/licenses/
version: 1.16
