---
name: Test-RDF
version: 0.0.3
author:
  - 'Michael Hendricks  <michael@palmcluster.org>'
abstract: Test RDF data for validity and equality
license: perl
requires:
  RDF::Redland: 1.000101
build_requires:
  Test::More: 0
provides:
  Test::RDF:
    file: lib/Test/RDF.pm
    version: 0.0.3
generated_by: Module::Build version 0.2611
